/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Stitch Palette (Light Blue)
        "primary": "#0284c7",
        "primary-container": "#0ea5e9",
        "on-primary": "#ffffff",
        "on-primary-container": "#0369a1",
        "primary-fixed": "#e0f2fe",
        "primary-fixed-dim": "#bae6fd",
        "on-primary-fixed": "#082f49",
        "on-primary-fixed-variant": "#0284c7",
        "inverse-primary": "#7dd3fc",

        "secondary": "#565e74",
        "secondary-container": "#dae2fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",

        "tertiary": "#374559",
        "tertiary-container": "#4f5d71",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c7d6ee",
        "tertiary-fixed": "#d5e3fc",
        "tertiary-fixed-dim": "#b9c7df",
        "on-tertiary-fixed": "#0d1c2e",
        "on-tertiary-fixed-variant": "#3a485b",

        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#0ea5e9",

        "on-surface": "#0b1c30",
        "on-surface-variant": "#434655",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",

        "outline": "#747686",
        "outline-variant": "#c4c5d7",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        // Semantic status tokens for DocChase operational workflow
        "status-complete": "#15803d",
        "status-complete-bg": "#ecfdf5",
        "status-complete-border": "#bbf7d0",
        "status-waiting": "#b45309",
        "status-waiting-bg": "#fffbeb",
        "status-waiting-border": "#fde68a",
        "status-overdue": "#b91c1c",
        "status-overdue-bg": "#fef2f2",
        "status-overdue-border": "#fecaca",
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xxs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'gutter': '1rem',
        'gutter-lg': '1.5rem',
        'margin': '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-mobile': ['Inter', 'sans-serif'],
        'tabular-numeric': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'display-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'tabular-numeric': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
