/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Monochrome SaaS Palette (Black / White / Charcoal / Gray)
        "primary": "#09090b",
        "primary-container": "#18181b",
        "on-primary": "#ffffff",
        "on-primary-container": "#f4f4f5",
        "primary-fixed": "#f4f4f5",
        "primary-fixed-dim": "#e4e4e7",
        "on-primary-fixed": "#09090b",
        "on-primary-fixed-variant": "#27272a",
        "inverse-primary": "#ffffff",

        "secondary": "#71717a",
        "secondary-container": "#f4f4f5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#18181b",
        "secondary-fixed": "#f4f4f5",
        "secondary-fixed-dim": "#e4e4e7",
        "on-secondary-fixed": "#09090b",
        "on-secondary-fixed-variant": "#52525b",

        "tertiary": "#27272a",
        "tertiary-container": "#3f3f46",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f4f4f5",
        "tertiary-fixed": "#f4f4f5",
        "tertiary-fixed-dim": "#e4e4e7",
        "on-tertiary-fixed": "#09090b",
        "on-tertiary-fixed-variant": "#27272a",

        "surface": "#ffffff",
        "surface-dim": "#f4f4f5",
        "surface-bright": "#ffffff",
        "surface-variant": "#f4f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fafafa",
        "surface-container": "#f4f4f5",
        "surface-container-high": "#e4e4e7",
        "surface-container-highest": "#d4d4d8",
        "inverse-surface": "#18181b",
        "inverse-on-surface": "#fafafa",
        "surface-tint": "#09090b",

        "on-surface": "#09090b",
        "on-surface-variant": "#71717a",
        "background": "#ffffff",
        "on-background": "#09090b",

        "outline": "#e4e4e7",
        "outline-variant": "#d4d4d8",

        "error": "#e11d48",
        "error-container": "#ffe4e6",
        "on-error": "#ffffff",
        "on-error-container": "#9f1239",

        // Semantic status tokens for DocChase operational workflow
        "status-complete": "#10b981",
        "status-complete-bg": "#ecfdf5",
        "status-complete-border": "#a7f3d0",
        "status-waiting": "#f59e0b",
        "status-waiting-bg": "#fffbeb",
        "status-waiting-border": "#fde68a",
        "status-overdue": "#f43f5e",
        "status-overdue-bg": "#fff1f2",
        "status-overdue-border": "#fecdd3",
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'space-xxs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'gutter': '1rem',
        'gutter-lg': '1.5rem',
        'margin': '1rem',
        'margin-md': '1.5rem',
        'margin-lg': '2rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-mobile': ['Inter', 'sans-serif'],
        'tabular-numeric': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'display-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.005em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
        'tabular-numeric': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
